package(default_visibility = ["//visibility:private"])

java_test(
    name = "DiffCommandTest",
    srcs = [
        "DiffCommandTest.java",
    ],
    test_class = "com.google.startupos.tools.aa.DiffCommandTest",
    deps = [
        "//third_party/maven/junit:junit",
        "//third_party/maven/org/mockito:mockito_core",
        "//third_party/maven/com/google/guava:guava",
        "//third_party/maven/com/google/jimfs",
        "//third_party/maven/org/objenesis:objenesis",
        "//third_party/maven/com/google/dagger:dagger",
    ],
)
